### ISSUE TITLE
服务器双网卡以后不能加入节点。 

### ISSUE THREAD

**Issue by skydeadpeng** [n9e/book#18]
transfer 下日志 ifconfig: `--help' gives usage information.:5841 fail: ens34: 未知的主机
ifconfig: `--help' gives usage information.:5841 get connection fail: conn <nil>, err address ens34: 未知的主机
ifconfig: `--help' gives usage information.:5841: too many colons in address. proc: Name:ens34: 未知的主机
ifconfig: `--help' gives usage information.:5841,Cnt:0,active:0,all:0,free:0

**Comment by UlricQin** [comment]
这个是因为系统各个模块配置的shell指令无法获取到机器ip。

进入部署目录的etc下，`grep ifconfig .`即可看到有多个配置文件里有相关shell，这个shell的作用是获取本机ip的，但是这个shell只是个示例，并不能解决所有的问题，有些机器网络环境比较复杂，就需要自己定制一个合适的shell了。

用自定义的shell，修改这几个配置文件，重启相关模块，就能解决这个问题了
