### ISSUE TITLE
入门级问题安装完怎么添加监控对象

### ISSUE THREAD

**Issue by R1hug0** [n9e/book#20]
对要监控的机器怎么接入夜莺,哪里有文档可以查看，怎么添加监控对象，需要安装agent还是？导入格式和规范呢

**Comment by UlricQin** [comment]
安装agent即可，n9e.didiyun.com有完善的文档，B站有视频

**Comment by R1hug0** [comment]
> 安装agent即可，n9e.didiyun.com有完善的文档，B站有视频

看了视频没有添加被监控的对象方面啊，agent安装这块，可能表述有问题

**Comment by UlricQin** [comment]
collector安装完了，就自动上报了，上报了就自动出现了对象列表里了。然后就可以挂载节点。
