### ISSUE TITLE
swcollector

### ISSUE THREAD

**Issue by fanzhe-0607** [n9e/book#21]
如何安装swcollector

**Comment by fanzhe-0607** [comment]
有没有视频教程或者安装教程

**Comment by UlricQin** [comment]
编译一下二进制即可，swcollector有个配置文件，需要按照swcollector提供的readme文档配置

**Comment by fanzhe-0607** [comment]
> 编译一下二进制即可，swcollector有个配置文件，需要按照swcollector提供的readme文档配置

非常感谢
