### ISSUE TITLE
Collector单独部署

### ISSUE THREAD

**Issue by shuchang-wang** [n9e/book#27]
启动失败：/home/n9e/n9e-collector (code=exited, status=203/EXEC)
[root@Nightingale etc]# systemctl status n9e-collector.service 
● n9e-collector.service - Nightingale collector
   Loaded: loaded (/usr/lib/systemd/system/n9e-collector.service; enabled; vendor preset: disabled)
   Active: active (running) since 一 2020-07-20 15:03:14 CST; 2ms ago
 Main PID: 73473 ((ollector))
    Tasks: 0
   Memory: 0B
   CGroup: /system.slice/n9e-collector.service
           └─73473 (ollector)

7月 20 15:03:14 open_falcon systemd[1]: Started Nightingale collector.
7月 20 15:03:14 open_falcon systemd[1]: n9e-collector.service: main process exited, code=exited, status=203/EXEC
7月 20 15:03:14 open_falcon systemd[1]: Unit n9e-collector.service entered failed state.
7月 20 15:03:14 open_falcon systemd[1]: n9e-collector.service failed.

[root@Nightingale etc]# systemctl status n9e-collector.service 
● n9e-collector.service - Nightingale collector
   Loaded: loaded (/usr/lib/systemd/system/n9e-collector.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since 一 2020-07-20 15:03:16 CST; 28ms ago
  Process: 73481 ExecStart=/home/n9e/n9e-collector (code=exited, status=203/EXEC)
 Main PID: 73481 (code=exited, status=203/EXEC)

7月 20 15:03:16 Nightingale systemd[1]: Unit n9e-collector.service entered failed state.
7月 20 15:03:16 Nightingale systemd[1]: n9e-collector.service failed.

**Comment by UlricQin** [comment]
/home/n9e/n9e-collector 手工执行，不用systemd托管看看报的什么错，另外可以参考B站视频，怎么安装讲的很清楚了
