### ISSUE TITLE
源码调试问题

### ISSUE THREAD

**Issue by ntuwang** [n9e/book#55]
在goland 调试的时候，runner.Cwd 得到的路径是 /private/var/folders/16/4t4szn4n6rbblq528_m2lsqh0000gn/T/GoLand， 会导致启动失败，需要手动修改了路径，官方可以看下算不算bug

**Comment by UlricQin** [comment]
不算，夜莺按照约定的路径读取配置，goland把二进制自动挪了位置，不能算是夜莺的锅
